
---
- hosts: servers
  remote_user: user
  become: yes
  become_user: root

  vars_files:
    - vars.yml

  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Upgrade existing packages
      apt: upgrade=dist

    - name: Install base packages
      apt: pkg=vim state=installed